server:
  port: 8085
spring:
  data:
    mongodb:
      username: ${MONGO_USER:niskuldeep}
      password: ${MONGO_PASSWORD:niskuldeep}
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: customer
      authentication-database: admin

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

