server:
  port: 8090
spring:
  data:
    mongodb:
      username: niskuldeep
      password: niskuldeep
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin