global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'microservices-ecommerce'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Config Server
  - job_name: 'config-server'
    static_configs:
      - targets: ['localhost:8888']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # Service Discovery (Eureka)
  - job_name: 'discovery-service'
    static_configs:
      - targets: ['localhost:8761']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # API Gateway
  - job_name: 'gateway-service'
    static_configs:
      - targets: ['localhost:8222']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # Order Service
  - job_name: 'order-service'
    static_configs:
      - targets: ['localhost:8070']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # Payment Service
  - job_name: 'payment-service'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # Product Service
  - job_name: 'product-service'
    static_configs:
      - targets: ['localhost:8090']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # Customer Service
  - job_name: 'customer-service'
    static_configs:
      - targets: ['localhost:8085']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # Notification Service
  - job_name: 'notification-service'
    static_configs:
      - targets: ['localhost:8095']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

